---
title: "Analise Give Me Some Credit"
author: "Marcio Cruz"
date: "24/08/2021"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# inicialização -----------------------------------------------------------
wd <- Sys.getenv("RWD")

if (!file.exists(wd)) {
  stop(paste("O diretorio definido na variavel de ambiente RWD nao foi encontrado",wd, sep="="))
} 

setwd(wd)
getwd()

rm(list = ls())

options(scipen=999)
options(width = 1024)

library(Metrics)
library(MLmetrics)
library("stringi")
library(knitr)
library(InformationValue)
library(moments)
library(pander)
library(dplyr)
library(cutpointr)
library(Information)
library(readxl) #Avisar o R que utilizará este pacote. Deve-se avisar toda vez que abrir o R
library(HH)
library(expss)
library(arules)
library(smbinning)
library(scorecard)
library(ggplot2)
library(ggpubr)
theme_set(theme_pubr())

```

# Case
Melhorar a pontuação, prevendo a probabilidade de alguém sofrer dificuldades financeiras nos próximos dois anos.

```{r echo = F}
treino <- read_excel("doc/GiveMeSomeCredit - Me De Algum Crédito.xlsx", sheet="Treino")
teste <- read_excel("doc/GiveMeSomeCredit - Me De Algum Crédito.xlsx", sheet="Teste")


$`ID_Cliente` <- NULL
df_inadimplentes$`ID_Cliente` <- NULL
df_adimplentes$`ID_Cliente` <- NULL

```
